services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    volumes:
      - app_logs:/app/logs
    networks:
      - internal_network
      - api-gateway_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - api-gateway_network
    depends_on:
      - app

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - api-gateway_network

  promtail:
    image: grafana/promtail:latest
    ports:
      - "9080:9080"
    volumes:
      - app_logs:/host_logs
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true
    depends_on: [loki, app]
    networks:
      - api-gateway_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on: [prometheus]
    networks:
      - api-gateway_network

  
volumes:
  app_logs:
  prometheus_data:
  grafana_data:

networks:
  api-gateway_network:
    driver: bridge
  internal_network:
    external: true