services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    command: sh -c "uvicorn api.main:app --host 0.0.0.0 --port 8000"
    networks:
      - internal_network

networks:
  internal_network:
    external: true