server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: api_gateway
  static_configs:
  - targets:
      - localhost
    labels:
      job: api_gateway
      __path__: /host_logs/app.log

  pipeline_stages:
    - json:
        expressions:
          level: level
          msg: message
