"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class AuthRegisterRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    email: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        email: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "password", b"password", "username", b"username"]) -> None: ...

global___AuthRegisterRequest = AuthRegisterRequest

@typing.final
class AuthRegisterResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    email: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        email: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "id", b"id", "username", b"username"]) -> None: ...

global___AuthRegisterResponse = AuthRegisterResponse

@typing.final
class AuthLoginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERNAME_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    username: builtins.str
    password: builtins.str
    def __init__(
        self,
        *,
        username: builtins.str = ...,
        password: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["password", b"password", "username", b"username"]) -> None: ...

global___AuthLoginRequest = AuthLoginRequest

@typing.final
class AuthLoginResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    REFRESH_TOKEN_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    refresh_token: builtins.str
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        refresh_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "refresh_token", b"refresh_token"]) -> None: ...

global___AuthLoginResponse = AuthLoginResponse

@typing.final
class RefreshAccessTokenRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PayloadEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def payload(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        payload: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload"]) -> None: ...

global___RefreshAccessTokenRequest = RefreshAccessTokenRequest

@typing.final
class RefreshAccessTokenResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token"]) -> None: ...

global___RefreshAccessTokenResponse = RefreshAccessTokenResponse

@typing.final
class CurrentUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PayloadEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    PAYLOAD_FIELD_NUMBER: builtins.int
    @property
    def payload(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        payload: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["payload", b"payload"]) -> None: ...

global___CurrentUserRequest = CurrentUserRequest

@typing.final
class User(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_SUPERUSER_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    email: builtins.str
    is_active: builtins.bool
    is_superuser: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        email: builtins.str = ...,
        is_active: builtins.bool = ...,
        is_superuser: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "id", b"id", "is_active", b"is_active", "is_superuser", b"is_superuser", "username", b"username"]) -> None: ...

global___User = User

@typing.final
class CurrentUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_FIELD_NUMBER: builtins.int
    @property
    def user(self) -> global___User: ...
    def __init__(
        self,
        *,
        user: global___User | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["user", b"user"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["user", b"user"]) -> None: ...

global___CurrentUserResponse = CurrentUserResponse

@typing.final
class HealthCheckResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ChecksEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    STATUS_FIELD_NUMBER: builtins.int
    CHECKS_FIELD_NUMBER: builtins.int
    status: builtins.str
    @property
    def checks(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        status: builtins.str = ...,
        checks: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["checks", b"checks", "status", b"status"]) -> None: ...

global___HealthCheckResponse = HealthCheckResponse

@typing.final
class CreateUserByAdminRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_SUPERUSER_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    username: builtins.str
    email: builtins.str
    password: builtins.str
    is_active: builtins.bool
    is_superuser: builtins.bool
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        username: builtins.str = ...,
        email: builtins.str = ...,
        password: builtins.str = ...,
        is_active: builtins.bool = ...,
        is_superuser: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "email", b"email", "is_active", b"is_active", "is_superuser", b"is_superuser", "password", b"password", "username", b"username"]) -> None: ...

global___CreateUserByAdminRequest = CreateUserByAdminRequest

@typing.final
class CreateUserByAdminResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_SUPERUSER_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    email: builtins.str
    is_active: builtins.bool
    is_superuser: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        email: builtins.str = ...,
        is_active: builtins.bool = ...,
        is_superuser: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "id", b"id", "is_active", b"is_active", "is_superuser", b"is_superuser", "username", b"username"]) -> None: ...

global___CreateUserByAdminResponse = CreateUserByAdminResponse

@typing.final
class UpdateUserByAdminRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    PASSWORD_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_SUPERUSER_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    id: builtins.str
    username: builtins.str
    email: builtins.str
    password: builtins.str
    is_active: builtins.bool
    is_superuser: builtins.bool
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        id: builtins.str = ...,
        username: builtins.str | None = ...,
        email: builtins.str | None = ...,
        password: builtins.str | None = ...,
        is_active: builtins.bool | None = ...,
        is_superuser: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_email", b"_email", "_is_active", b"_is_active", "_is_superuser", b"_is_superuser", "_password", b"_password", "_username", b"_username", "email", b"email", "is_active", b"is_active", "is_superuser", b"is_superuser", "password", b"password", "username", b"username"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_email", b"_email", "_is_active", b"_is_active", "_is_superuser", b"_is_superuser", "_password", b"_password", "_username", b"_username", "access_token", b"access_token", "email", b"email", "id", b"id", "is_active", b"is_active", "is_superuser", b"is_superuser", "password", b"password", "username", b"username"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_email", b"_email"]) -> typing.Literal["email"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_is_active", b"_is_active"]) -> typing.Literal["is_active"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_is_superuser", b"_is_superuser"]) -> typing.Literal["is_superuser"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_password", b"_password"]) -> typing.Literal["password"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_username", b"_username"]) -> typing.Literal["username"] | None: ...

global___UpdateUserByAdminRequest = UpdateUserByAdminRequest

@typing.final
class UpdateUserByAdminResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    EMAIL_FIELD_NUMBER: builtins.int
    IS_ACTIVE_FIELD_NUMBER: builtins.int
    IS_SUPERUSER_FIELD_NUMBER: builtins.int
    id: builtins.str
    username: builtins.str
    email: builtins.str
    is_active: builtins.bool
    is_superuser: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        username: builtins.str = ...,
        email: builtins.str = ...,
        is_active: builtins.bool = ...,
        is_superuser: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["email", b"email", "id", b"id", "is_active", b"is_active", "is_superuser", b"is_superuser", "username", b"username"]) -> None: ...

global___UpdateUserByAdminResponse = UpdateUserByAdminResponse

@typing.final
class DeleteUserByAdminRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token", "id", b"id"]) -> None: ...

global___DeleteUserByAdminRequest = DeleteUserByAdminRequest

@typing.final
class DeleteUserByAdminResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    IS_DELETED_FIELD_NUMBER: builtins.int
    id: builtins.str
    is_deleted: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        is_deleted: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "is_deleted", b"is_deleted"]) -> None: ...

global___DeleteUserByAdminResponse = DeleteUserByAdminResponse

@typing.final
class GetAllUsersByAdminRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACCESS_TOKEN_FIELD_NUMBER: builtins.int
    access_token: builtins.str
    def __init__(
        self,
        *,
        access_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["access_token", b"access_token"]) -> None: ...

global___GetAllUsersByAdminRequest = GetAllUsersByAdminRequest

@typing.final
class GetAllUsersByAdminResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USERS_FIELD_NUMBER: builtins.int
    @property
    def users(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___User]: ...
    def __init__(
        self,
        *,
        users: collections.abc.Iterable[global___User] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["users", b"users"]) -> None: ...

global___GetAllUsersByAdminResponse = GetAllUsersByAdminResponse
