"""files: make url nullable True;

Revision ID: 154784eebcc6
Revises: 7c2c637dde1e
Create Date: 2025-09-10 23:45:42.018808

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '154784eebcc6'
down_revision: Union[str, Sequence[str], None] = '7c2c637dde1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
