"""files: make url unique;

Revision ID: 7c2c637dde1e
Revises: 8fcfbee1d84c
Create Date: 2025-09-10 23:27:31.966090

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7c2c637dde1e'
down_revision: Union[str, Sequence[str], None] = '8fcfbee1d84c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'files', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    # ### end Alembic commands ###
