"""files: add key field;

Revision ID: 9a14a11877a7
Revises: 154784eebcc6
Create Date: 2025-09-11 00:52:32.342857

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a14a11877a7'
down_revision: Union[str, Sequence[str], None] = '154784eebcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('key', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'files', ['key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    op.drop_column('files', 'key')
    # ### end Alembic commands ###
