# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto.media import media_pb2 as media__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in media_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadAvatar = channel.unary_unary(
                '/media.Media/UploadAvatar',
                request_serializer=media__pb2.UploadAvatarRequest.SerializeToString,
                response_deserializer=media__pb2.UploadAvatarResponse.FromString,
                _registered_method=True)
        self.GetFileUrl = channel.unary_unary(
                '/media.Media/GetFileUrl',
                request_serializer=media__pb2.GetFileUrlRequest.SerializeToString,
                response_deserializer=media__pb2.GetFileUrlResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/media.Media/DeleteFile',
                request_serializer=media__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=media__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/media.Media/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=media__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class MediaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadAvatar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadAvatar,
                    request_deserializer=media__pb2.UploadAvatarRequest.FromString,
                    response_serializer=media__pb2.UploadAvatarResponse.SerializeToString,
            ),
            'GetFileUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileUrl,
                    request_deserializer=media__pb2.GetFileUrlRequest.FromString,
                    response_serializer=media__pb2.GetFileUrlResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=media__pb2.DeleteFileRequest.FromString,
                    response_serializer=media__pb2.DeleteFileResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=media__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'media.Media', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('media.Media', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Media(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/media.Media/UploadAvatar',
            media__pb2.UploadAvatarRequest.SerializeToString,
            media__pb2.UploadAvatarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/media.Media/GetFileUrl',
            media__pb2.GetFileUrlRequest.SerializeToString,
            media__pb2.GetFileUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/media.Media/DeleteFile',
            media__pb2.DeleteFileRequest.SerializeToString,
            media__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary( # type: ignore
            request,
            target,
            '/media.Media/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            media__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
