services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "${GRPC__PORT}:${GRPC__PORT}"
    depends_on: [postgres]
    command: sh -c "python -m alembic upgrade head && python -m rpc.main"
    networks:
      - user_network
      - internal_network

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user_network

volumes:
  postgres_data:

networks:
  user_network:
    driver: bridge
  internal_network:
    external: true