from typing import Protocol


class BaseBrokerService(Protocol):
    async def start(self) -> None: ...

    async def publish(self, data: dict, routing_key: str) -> None: ...

    async def stop(self) -> None: ...

    async def health_check(self) -> bool: ...