from typing import Protocol


class BaseBrokerService(Protocol):
    async def start(self) -> None: ...

    async def publish(self, data: dict, routing_key: str) -> None: ...

    async def publish_user_created(self, user: dict) -> None: ...

    async def stope(self) -> None: ...
