from typing import Protocol


class BrokerService(Protocol):
    is_alive = False

    async def start(self) -> None: ...

    async def publish(self, data: dict, routing_key: str, save_fallback_message: bool = True) -> bool: ...

    async def publish_user_created(self, user: dict) -> bool: ...

    async def stop(self) -> None: ...

    async def health_check(self) -> bool: ...