"""auth: add username and emal field; delete user_id field;

Revision ID: 1c17399aa48d
Revises: 4d96892678d8
Create Date: 2025-09-01 14:05:35.056958

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1c17399aa48d'
down_revision: Union[str, Sequence[str], None] = '4d96892678d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('username', sa.String(length=64), nullable=False))
    op.add_column('auth', sa.Column('email', sa.String(length=64), nullable=False))
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth')
    op.drop_column('auth', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_auth_user_id'), 'auth', ['user_id'], unique=True)
    op.drop_column('auth', 'email')
    op.drop_column('auth', 'username')
    # ### end Alembic commands ###
