"""auth: add index to username and email fields;

Revision ID: b011b40cc98b
Revises: 1c17399aa48d
Create Date: 2025-09-01 14:13:19.234506

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b011b40cc98b'
down_revision: Union[str, Sequence[str], None] = '1c17399aa48d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_email'), 'auth', ['email'], unique=True)
    op.create_index(op.f('ix_auth_username'), 'auth', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_username'), table_name='auth')
    op.drop_index(op.f('ix_auth_email'), table_name='auth')
    # ### end Alembic commands ###
