# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default() # noqa: F401




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"H\n\x13\x41uthRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"C\n\x14\x41uthRegisterResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"6\n\x10\x41uthLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"@\n\x11\x41uthLoginResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\"\x85\x01\n\x19RefreshAccessTokenRequest\x12\x38\n\x07payload\x18\x01 \x03(\x0b\x32\'.RefreshAccessTokenRequest.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\x1aRefreshAccessTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"w\n\x12\x43urrentUserRequest\x12\x31\n\x07payload\x18\x01 \x03(\x0b\x32 .CurrentUserRequest.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\\\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x12\x14\n\x0cis_superuser\x18\x05 \x01(\x08\"*\n\x13\x43urrentUserResponse\x12\x13\n\x04user\x18\x01 \x01(\x0b\x32\x05.User2\x80\x02\n\x04\x41uth\x12;\n\x0cRegisterUser\x12\x14.AuthRegisterRequest\x1a\x15.AuthRegisterResponse\x12\x32\n\tLoginUser\x12\x11.AuthLoginRequest\x1a\x12.AuthLoginResponse\x12M\n\x12RefreshAccessToken\x12\x1a.RefreshAccessTokenRequest\x1a\x1b.RefreshAccessTokenResponse\x12\x38\n\x0b\x43urrentUser\x12\x13.CurrentUserRequest\x1a\x14.CurrentUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REFRESHACCESSTOKENREQUEST_PAYLOADENTRY']._loaded_options = None
  _globals['_REFRESHACCESSTOKENREQUEST_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_CURRENTUSERREQUEST_PAYLOADENTRY']._loaded_options = None
  _globals['_CURRENTUSERREQUEST_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_AUTHREGISTERREQUEST']._serialized_start=14
  _globals['_AUTHREGISTERREQUEST']._serialized_end=86
  _globals['_AUTHREGISTERRESPONSE']._serialized_start=88
  _globals['_AUTHREGISTERRESPONSE']._serialized_end=155
  _globals['_AUTHLOGINREQUEST']._serialized_start=157
  _globals['_AUTHLOGINREQUEST']._serialized_end=211
  _globals['_AUTHLOGINRESPONSE']._serialized_start=213
  _globals['_AUTHLOGINRESPONSE']._serialized_end=277
  _globals['_REFRESHACCESSTOKENREQUEST']._serialized_start=280
  _globals['_REFRESHACCESSTOKENREQUEST']._serialized_end=413
  _globals['_REFRESHACCESSTOKENREQUEST_PAYLOADENTRY']._serialized_start=367
  _globals['_REFRESHACCESSTOKENREQUEST_PAYLOADENTRY']._serialized_end=413
  _globals['_REFRESHACCESSTOKENRESPONSE']._serialized_start=415
  _globals['_REFRESHACCESSTOKENRESPONSE']._serialized_end=465
  _globals['_CURRENTUSERREQUEST']._serialized_start=467
  _globals['_CURRENTUSERREQUEST']._serialized_end=586
  _globals['_CURRENTUSERREQUEST_PAYLOADENTRY']._serialized_start=367
  _globals['_CURRENTUSERREQUEST_PAYLOADENTRY']._serialized_end=413
  _globals['_USER']._serialized_start=588
  _globals['_USER']._serialized_end=680
  _globals['_CURRENTUSERRESPONSE']._serialized_start=682
  _globals['_CURRENTUSERRESPONSE']._serialized_end=724
  _globals['_AUTH']._serialized_start=727
  _globals['_AUTH']._serialized_end=983
# @@protoc_insertion_point(module_scope)
