"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CreateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    first_name: builtins.str
    last_name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        first_name: builtins.str | None = ...,
        last_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "last_name", b"last_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "id", b"id", "last_name", b"last_name"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_first_name", b"_first_name"]) -> typing.Literal["first_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_name", b"_last_name"]) -> typing.Literal["last_name"] | None: ...

global___CreateUserRequest = CreateUserRequest

@typing.final
class CreateUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    first_name: builtins.str
    last_name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        first_name: builtins.str | None = ...,
        last_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "last_name", b"last_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "id", b"id", "last_name", b"last_name"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_first_name", b"_first_name"]) -> typing.Literal["first_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_name", b"_last_name"]) -> typing.Literal["last_name"] | None: ...

global___CreateUserResponse = CreateUserResponse

@typing.final
class UpdateUserRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    first_name: builtins.str
    last_name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        first_name: builtins.str | None = ...,
        last_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "last_name", b"last_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "id", b"id", "last_name", b"last_name"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_first_name", b"_first_name"]) -> typing.Literal["first_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_name", b"_last_name"]) -> typing.Literal["last_name"] | None: ...

global___UpdateUserRequest = UpdateUserRequest

@typing.final
class UpdateUserResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    FIRST_NAME_FIELD_NUMBER: builtins.int
    LAST_NAME_FIELD_NUMBER: builtins.int
    id: builtins.str
    first_name: builtins.str
    last_name: builtins.str
    def __init__(
        self,
        *,
        id: builtins.str = ...,
        first_name: builtins.str | None = ...,
        last_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "last_name", b"last_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_first_name", b"_first_name", "_last_name", b"_last_name", "first_name", b"first_name", "id", b"id", "last_name", b"last_name"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_first_name", b"_first_name"]) -> typing.Literal["first_name"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_last_name", b"_last_name"]) -> typing.Literal["last_name"] | None: ...

global___UpdateUserResponse = UpdateUserResponse
