# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"m\n\x11\x43reateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_name\"n\n\x12\x43reateUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_name\"m\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_name\"n\n\x12UpdateUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_first_nameB\x0c\n\n_last_name2{\n\x0bUserService\x12\x35\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x13.CreateUserResponse\x12\x35\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=14
  _globals['_CREATEUSERREQUEST']._serialized_end=123
  _globals['_CREATEUSERRESPONSE']._serialized_start=125
  _globals['_CREATEUSERRESPONSE']._serialized_end=235
  _globals['_UPDATEUSERREQUEST']._serialized_start=237
  _globals['_UPDATEUSERREQUEST']._serialized_end=346
  _globals['_UPDATEUSERRESPONSE']._serialized_start=348
  _globals['_UPDATEUSERRESPONSE']._serialized_end=458
  _globals['_USERSERVICE']._serialized_start=460
  _globals['_USERSERVICE']._serialized_end=583
# @@protoc_insertion_point(module_scope)
